#This is the file that is generated by PyQt4 by running pyuic4 A.ui > A.py where A.ui is the XML file that is generated by QT Designer

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'A.ui'
#
# Created: Thu Oct  5 19:03:33 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
#method for definition of the UI elements 
    def setupUi(self, MainWindow):

        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(601, 460)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../pi.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
	
#definition of the push buttons and the display boxes with the object name and properties selected in QT Designer
        
	#The button to start showing values every 5 seconds
	self.showhum_button = QtGui.QPushButton(self.centralwidget) 
        self.showhum_button.setGeometry(QtCore.QRect(10, 10, 251, 61))
        self.showhum_button.setObjectName(_fromUtf8("showhum_button"))
	#The textbox to display the temp and humidity values every 5 seconds 
        self.showhum_window = QtGui.QTextEdit(self.centralwidget)
        self.showhum_window.setGeometry(QtCore.QRect(280, 0, 281, 115))
        self.showhum_window.setObjectName(_fromUtf8("showhum_window"))
	#The button to close the QT GUI
        self.close_button = QtGui.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(520, 300, 81, 21))
        self.close_button.setObjectName(_fromUtf8("close_button"))
	#The button to show the average humidity
        self.avghum_button = QtGui.QPushButton(self.centralwidget)
        self.avghum_button.setGeometry(QtCore.QRect(20, 80, 181, 31))
        self.avghum_button.setObjectName(_fromUtf8("avghum_button"))
	#The combo box to change the number of iterations
        self.cb = QtGui.QComboBox(self.centralwidget)
        self.cb.setGeometry(QtCore.QRect(430, 300, 85, 31))
        self.cb.setObjectName(_fromUtf8("cb"))  
	self.cb.addItem(_fromUtf8(""))
        self.cb.addItem(_fromUtf8(""))
        self.cb.addItem(_fromUtf8(""))
	self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 300, 211, 31))
        self.label.setObjectName(_fromUtf8("label"))
        #The button to show the average humidity    
	self.avgtemp_button = QtGui.QPushButton(self.centralwidget)
        self.avgtemp_button.setGeometry(QtCore.QRect(20, 120, 181, 31))
        self.avgtemp_button.setObjectName(_fromUtf8("avgtemp_button"))
        #The button to show the max humidity
	self.maxhum_button = QtGui.QPushButton(self.centralwidget)
        self.maxhum_button.setGeometry(QtCore.QRect(20, 160, 181, 31))
        self.maxhum_button.setObjectName(_fromUtf8("maxhum_button"))
	#The button to show the maximum temperature
        self.maxtemp_button = QtGui.QPushButton(self.centralwidget)
        self.maxtemp_button.setGeometry(QtCore.QRect(20, 200, 181, 31))
        self.maxtemp_button.setObjectName(_fromUtf8("maxtemp_button"))
	#The button to show the minimum humidity
        self.minhum_button = QtGui.QPushButton(self.centralwidget)
        self.minhum_button.setGeometry(QtCore.QRect(20, 240, 181, 31))
        self.minhum_button.setObjectName(_fromUtf8("minhum_button"))
        #The button to show the minimum humidity
	self.mintemp_button = QtGui.QPushButton(self.centralwidget)
        self.mintemp_button.setGeometry(QtCore.QRect(20, 280, 181, 31))
        self.mintemp_button.setObjectName(_fromUtf8("mintemp_button"))
	#The button to change units of temperature
        self.CtoF_button = QtGui.QPushButton(self.centralwidget)
        self.CtoF_button.setGeometry(QtCore.QRect(230, 240, 181, 31))
        self.CtoF_button.setObjectName(_fromUtf8("CtoF_button"))
	#The textbox to display any of the above values	
        self.display = QtGui.QTextEdit(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(230, 120, 341, 111))
        self.display.setObjectName(_fromUtf8("display"))
	#The button to show the last value of humidity
        self.lasthum_button = QtGui.QPushButton(self.centralwidget)
        self.lasthum_button.setGeometry(QtCore.QRect(20, 320, 191, 31))
        self.lasthum_button.setObjectName(_fromUtf8("lasthum_button"))
        #The button to show the last value of temperature
	self.lasttemp_button = QtGui.QPushButton(self.centralwidget)
        self.lasttemp_button.setGeometry(QtCore.QRect(20, 360, 201, 31))
        self.lasttemp_button.setObjectName(_fromUtf8("lasttemp_button"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
	#method to display the corresponding text on each widget
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperature-Humidity monitoring device", None))
        self.showhum_button.setText(_translate("MainWindow", "Current Humidity and Temperature", None))
        self.close_button.setText(_translate("MainWindow", "Close", None))
        self.avghum_button.setText(_translate("MainWindow", "Average Humidity", None))
        self.cb.setItemText(0, _translate("MainWindow", "5", None))
        self.cb.setItemText(1, _translate("MainWindow", "10", None))
        self.cb.setItemText(2, _translate("MainWindow", "15", None))
        self.label.setText(_translate("MainWindow", "Change number of Iterations:", None))
        self.avgtemp_button.setText(_translate("MainWindow", "Average Temperature", None))
        self.maxhum_button.setText(_translate("MainWindow", "Max Humidity", None))
        self.maxtemp_button.setText(_translate("MainWindow", "Max Temperature", None))
        self.minhum_button.setText(_translate("MainWindow", "Min Humidity", None))
        self.mintemp_button.setText(_translate("MainWindow", "Min Temperature", None))
        self.CtoF_button.setText(_translate("MainWindow", "C <-> F", None))
        self.lasthum_button.setText(_translate("MainWindow", "Last value of Humidity", None))
        self.lasttemp_button.setText(_translate("MainWindow", "Last value of Temperature", None))

